### ISSUE TITLE
Issue installing with mops

### ISSUE THREAD

**Issue by tomijaga** [canscale/StableHeapBTreeMap#17]
Hello @ByronBecker,

I encountered a problem while installing this package using Mops. 
I noticed the [vessel configuration](https://github.com/kritzcreek/motoko-matchers/blob/v1.2.0/package-set.dhall) for version `1.2.0` of the `matchers` dependency is no longer available.
Changing to version `1.3.0` might help resolve this issue. 
It worked for me, but I had to manually switch to version `1.3.0` in the hidden `.mops` directory.

**Comment by ByronBecker** [comment]
Hey, thanks for the update @tomijaga. Did you run into the issue installing this package directly or through CanDB?

I just bumped the version to `1.3.0` in https://github.com/canscale/StableHeapBTreeMap/pull/18.

**Comment by tomijaga** [comment]
Nice! I can confirm that it installs fine now.

I ran into the issue when installing this package directly.
